# Generated by Django 2.0 on 2017-12-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=20, verbose_name='考试科目')),
                ('total_score', models.IntegerField(blank=True, null=True, verbose_name='总分')),
                ('intro', models.TextField(default='', verbose_name='科目简介')),
            ],
            options={
                'verbose_name': '考试科目',
                'verbose_name_plural': '考试科目',
                'ordering': ['course'],
            },
        ),
        migrations.CreateModel(
            name='TestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, null=True, verbose_name='题目序号')),
                ('questions', models.TextField(default='', verbose_name='题目内容')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分值')),
                ('questions_type', models.CharField(max_length=20, verbose_name='题目类型')),
                ('answer', models.TextField(default='', verbose_name='标准答案')),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_taking.Test')),
            ],
            options={
                'verbose_name': '考试科目',
                'verbose_name_plural': '考试科目',
                'ordering': ['course_id', 'serial_number'],
            },
        ),
    ]
