# Generated by Django 2.0 on 2017-12-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_taking', '0004_auto_20171215_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='stage',
            field=models.CharField(blank=True, choices=[('f', '第一阶段'), ('s', '第二阶段'), ('t', '第三阶段')], max_length=20, verbose_name='阶段'),
        ),
    ]
