# Generated by Django 2.0 on 2017-12-19 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_taking', '0010_auto_20171216_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True, default='', verbose_name='答案')),
                ('update_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
                'ordering': ['update_user', 'question_id'],
            },
        ),
        migrations.AlterField(
            model_name='testdetail',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_taking.Test', verbose_name='科目编号'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_taking.TestDetail', verbose_name='题目编号'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='修改者'),
        ),
    ]
