# Generated by Django 2.0 on 2017-12-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_taking', '0012_auto_20171219_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='create_user',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='答题者'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='update_time',
            field=models.DateField(blank=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='update_user',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='修改者'),
        ),
    ]
