# Generated by Django 2.0 on 2017-12-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_taking', '0013_auto_20171219_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_taking.Test', verbose_name='科目编号'),
        ),
    ]
