# Generated by Django 2.0 on 2017-12-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_taking', '0014_useranswer_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdetail',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='question_id',
            new_name='question',
        ),
    ]
