# Generated by Django 2.0 on 2017-12-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_taking', '0017_auto_20171219_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='create_time',
            field=models.DateTimeField(verbose_name='答题时间'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_answer',
            field=models.TextField(blank=True, default='', null=True, verbose_name='答案'),
        ),
    ]
